name: matrix-workflow
on: push
jobs:
  build:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install nodejs
        uses: actions/setup-node@v3
      - name: install dependencies
        run : |
          npm ci
      - name: build node
        run: |
          npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy workflow
        uses: /home/ubuntu/git/17-github-matrix/.github/workflows/reusable.yml