name: matrix-workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build completed"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deploy workflow
        uses: ./.github/workflows/reusable.yml