name: matrix-workflow
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [12,13,14]
        os: [ubuntu-latest,windows-latest]
    runs-on: ${{ matrix.node-version }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.os }}
      - name: install dependencies
        run : |
          node ci
      - name: build node
        run: |
          node run build