name: deploy

on:
  workflow_call:
    inputs:
      artifacts-name:
        description: "Artifact name to deploy"
        required: true
        type: string
        default: dist
    outputs:
      print-out:
        description: "print the output of job"
        value: ${{ jobs.deploy.outputs.outcome }}
        

jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-out.outputs.set-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifacts-name }}
          path: dist
      - name: List files
        run: ls -l dist

      - name: Output information
        run: echo "Deploying and uploading..."
      - name: print output
        id: set-out
        run: echo "set-result=success" >> $GITHUB_OUTPUT
